CREATE TABLE IF NOT EXISTS user_control (
    id_user_control INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE KEY,
    senha VARCHAR(60) NOT NULL,
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS cliente (
    id_cliente INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE KEY,
    senha VARCHAR(60) NOT NULL,
    razao_social VARCHAR(255) NOT NULL,
    cnpj VARCHAR(14) NOT NULL UNIQUE KEY,
    nome VARCHAR(255) NOT NULL,
    token VARCHAR(32) NOT NULL,
    verificado BOOLEAN NOT NULL DEFAULT FALSE,
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS pedido (
	id_pedido INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    data DATE NOT NULL,
    numero INT(11) NOT NULL UNIQUE KEY,
    total DECIMAL(10,2),
    status ENUM("PENDENTE", "AGUARDANDO", "CANCELADO", "APROVADO", "FINALIZADO"),
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS equipamento (
    id_equipamento INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS teste (
    id_teste INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    status ENUM("EM_ANDAMENTO", "FINALIZADO"),
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

ALTER TABLE pedido
ADD COLUMN id_cliente INT(11) NOT NULL,
ADD FOREIGN KEY (id_cliente) REFERENCES cliente(id_cliente);

ALTER TABLE equipamento
ADD COLUMN id_pedido INT(11) NOT NULL,
ADD FOREIGN KEY (id_pedido) REFERENCES pedido(id_pedido);

ALTER TABLE teste
ADD COLUMN id_equipamento INT(11) NOT NULL,
ADD FOREIGN KEY (id_equipamento) REFERENCES equipamento(id_equipamento);

